app = "recibo-taxi"
primary_region = "gru"

[build]
  dockerfile = "dockerfile"   # minúsculo se seu arquivo é "dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
    protocol = "http"
