app = "recibotaxi"        # troque para o nome do seu app no Fly
primary_region = "gru"    # São Paulo

[build]
  # usa seu Dockerfile automaticamente

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
