app = "recibotaxi"        # troque se seu app tiver outro nome no Fly
primary_region = "gru"

[build]
  dockerfile = "dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
